class Food < ApplicationRecord
  belongs_to :pet

  FOOD = ["Ração seca", "Ração umida", "Ração natural", "Ração Medicamentosa"]
  BRAND = [
    "Adimax",
    "Alisul",
    "Bella Vita",
    "Biofresh",
    "Champ",
    "Cibau",
    "Dan Dog",
    "Dog Chow",
    "Dr. Stanley",
    "Equilibrio",
    "Evolve",
    "Faro",
    "Formula Natural",
    "Foster",
    "FriDog",
    "Golden",
    "Gran Plus",
    "Granvita",
    "Guabi Natural",
    "Heroi",
    "Hills",
    "Lester",
    "Lider",
    "Magic Pet",
    "Magnus",
    "Max",
    "Mon Petit Cheri",
    "N&D",
    "Naturalis",
    "Nero",
    "Optimum",
    "Origens",
    "Papapets",
    "Pedigree",
    "Pet Food Solution",
    "Premiatta",
    "Premier",
    "Pro Plan",
    "Qualiday",    
    "Quatree",
    "Royal Canin",
    "Special Dog",
    "Specialle Pet",
    "Spert Dog",
    "Supra",
    "Three Dogs",
    "Tibii",
    "Vet Life"
  ]
end
